In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
matrix = pd.read_csv('../data/beta_matrix_2024-01-01_2025-01-01_top50.csv').set_index('Ticker')
matrix

,UFPI,HYMC,ABAT,HYMCL,USAU,USGO,EU,IPX,AMWD,NB,...,TLN,OTTR,NFE,NEXT,SJW,INFN,CDZIP,NNE,NWE,ALCE
Ticker,,,,,,,,,,,,,,,,,,,,,
UFPI,1.000000,0.400641,0.069862,0.289755,0.746092,-0.464907,0.231779,0.041877,0.891955,0.575252,...,0.433951,0.520609,0.263500,0.552863,0.540858,0.704196,-0.497301,NaN,0.745554,-0.324495
HYMC,0.400641,1.000000,0.142288,0.183576,0.303395,0.602544,0.541550,-0.344446,0.328951,0.158555,...,0.247765,0.650708,0.681506,0.691727,0.168833,0.830058,-0.046983,NaN,-0.264505,-0.395644
ABAT,0.069862,0.142288,1.000000,-0.839743,-0.480638,-0.188233,0.668402,0.457811,0.175705,0.530757,...,0.337088,0.047634,0.170640,0.277047,0.698178,0.775765,0.189429,NaN,0.126654,-0.228034
HYMCL,0.289755,0.183576,-0.839743,1.000000,-0.586419,-0.257207,-0.183246,-0.755363,-0.071777,0.062766,...,-0.124098,0.023760,-0.350026,0.321602,0.030585,0.310486,0.076734,NaN,0.242429,0.374013
USAU,0.746092,0.303395,-0.480638,-0.586419,1.000000,0.559888,0.819386,0.010906,0.282621,0.549037,...,0.265188,0.373202,-0.129888,0.860991,0.076294,0.144757,0.042192,NaN,-0.177526,0.592777
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
INFN,0.704196,0.830058,0.775765,0.310486,0.144757,-0.379417,0.891028,0.564666,0.137195,0.745489,...,0.336555,-0.044225,0.149974,0.858507,0.640518,1.000000,0.654822,NaN,-0.076239,-0.044663
CDZIP,-0.497301,-0.046983,0.189429,0.076734,0.042192,0.369749,0.318166,-0.508290,0.172624,-0.086296,...,-0.443698,0.117140,-0.016626,0.011739,-0.182719,0.654822,1.000000,NaN,0.385010,0.581557
NNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
NWE,0.745554,-0.264505,0.126654,0.242429,-0.177526,-0.687845,-0.317478,0.569097,0.734547,0.517790,...,-0.239027,0.621783,0.116149,0.154167,0.091080,-0.076239,0.385010,NaN,1.000000,-0.057054
ALCE,-0.324495,-0.395644,-0.228034,0.374013,0.592777,0.683092,0.252523,-0.403530,0.119522,0.148318,...,0.701357,-0.622910,0.295628,0.414054,-0.508748,-0.044663,0.581557,NaN,-0.057054,1.000000

In [3]:
labels = pd.read_csv('../data/top_50_companies_by_sector.csv')
labels

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap (B),Country,IPO Year,Volume,Sector,Industry
0,UFPI,UFP Industries Inc. Common Stock,$115.67,-0.7900,-0.678%,7.024022,United States,1993.0,223820,Basic Materials,Forest Products
1,AMWD,American Woodmark Corporation Common Stock,$77.01,0.4800,0.627%,1.159322,United States,1986.0,168642,Basic Materials,Forest Products
2,IPX,IperionX Limited American Depositary Share,$26.52,0.1200,0.455%,0.682213,United States,NaN,50560,Basic Materials,Other Metals and Minerals
3,EU,enCore Energy Corp. Common Shares,$2.91,0.0600,2.105%,0.541518,United States,NaN,1091464,Basic Materials,Other Metals and Minerals
4,USGO,U.S. GoldMining Inc. Common stock,$12.59,1.7800,16.466%,0.156678,United States,2023.0,225247,Basic Materials,Precious Metals
...,...,...,...,...,...,...,...,...,...,...,...
524,VIVK,Vivakor Inc. Common Stock,$0.845,-0.0248,-2.851%,0.028424,United States,NaN,42549,Utilities,Environmental Services
525,SONM,Sonim Technologies Inc. Common Stock,$2.55,-0.0800,-3.042%,0.012423,United States,2019.0,15396,Utilities,Telecommunications Equipment
526,CLRO,ClearOne Inc. (DE) Common Stock,$0.4926,-0.0072,-1.441%,0.011807,United States,NaN,87213,Utilities,Telecommunications Equipment
527,SUNE,SUNation Energy Inc. Common Stock,$1.225,-0.0950,-7.197%,0.002223,United States,NaN,87057,Utilities,Telecommunications Equipment
528,ALCE,Alternus Clean Energy Inc. Class A Common Stock,$0.226,-0.0588,-20.646%,0.000000,United States,2022.0,1508724,Utilities,Power Generation

In [4]:
upper_triangle = np.triu(matrix, k=1)
row_indices, col_indices = np.where(np.abs(upper_triangle) > 0)
print(len(row_indices))
graph = pd.DataFrame({
    'source': matrix.columns[col_indices],
    'target': matrix.columns[row_indices],
    'value': upper_triangle[row_indices, col_indices],
    'abs': np.abs(upper_triangle[row_indices, col_indices])
})
graph

126253

       source target     value       abs
0        HYMC   UFPI  0.400641  0.400641
1        ABAT   UFPI  0.069862  0.069862
2       HYMCL   UFPI  0.289755  0.289755
3        USAU   UFPI  0.746092  0.746092
4        USGO   UFPI -0.464907  0.464907
...       ...    ...       ...       ...
126248    NWE   INFN -0.076239  0.076239
126249   ALCE   INFN -0.044663  0.044663
126250    NWE  CDZIP  0.385010  0.385010
126251   ALCE  CDZIP  0.581557  0.581557
126252   ALCE    NWE -0.057054  0.057054

[126253 rows x 4 columns]

In [5]:
node_degrees = pd.concat([graph['source'], graph['target']]).value_counts()

def filter_top_edges_for_node(df, node_degrees, min_edges=10):
    result_edges = []
    
    for node in node_degrees.index:
        # Get all edges for this node (both as source and target)
        node_edges = df[(df['source'] == node) | (df['target'] == node)]
        
        # Sort edges by absolute value to get strongest connections
        node_edges = node_edges.sort_values(by='value', key=abs, ascending=False)
        
        # If node has fewer than min_edges, keep all edges
        if len(node_edges) < min_edges:
            result_edges.append(node_edges)
        else:
            # Keep top min_edges edges
            result_edges.append(node_edges.head(min_edges))
    
    # Combine all edges and remove duplicates
    filtered_df = pd.concat(result_edges).drop_duplicates().reset_index(drop=True)
    
    # Verify each node has at least min_edges
    for node in node_degrees.index:
        node_edges = filtered_df[(filtered_df['source'] == node) | (filtered_df['target'] == node)]
        if len(node_edges) < min_edges:
            print(f"Warning: Node {node} still has only {len(node_edges)} edges")
    
    return filtered_df

links = filter_top_edges_for_node(graph, node_degrees, 2)
links

    source target     value       abs
0      HON   HYMC  0.925132  0.925132
1     PCVX   HYMC  0.873503  0.873503
2     FTNT   UNIT  0.951677  0.951677
3     MATW   UNIT  0.948850  0.948850
4      MDB  NHPBP  0.883992  0.883992
..     ...    ...       ...       ...
856   NYMT   MKTX  0.882206  0.882206
857   STRA   BPOP  0.957453  0.957453
858    PCH   UPST  0.942671  0.942671
859  HBANP   UPST  0.925034  0.925034
860   CPRT   UFPI  0.964489  0.964489

[861 rows x 4 columns]

In [6]:
relevant_nodes = set(links['source'].unique()) | set(links['target'].unique())
nodes = (labels[labels['Symbol']
        .isin(relevant_nodes)]
        [['Symbol', 'Sector', 'Market Cap (B)', 'Last Sale']]
        .rename(columns={
            'Symbol': 'id',
            'Sector': 'group',
            'Market Cap (B)': 'marketCap',
            'Last Sale': 'price'
            })
        )
nodes

       id            group  marketCap    price
0    UFPI  Basic Materials   7.024022  $115.67
1    AMWD  Basic Materials   1.159322   $77.01
2     IPX  Basic Materials   0.682213   $26.52
3      EU  Basic Materials   0.541518    $2.91
4    USGO  Basic Materials   0.156678   $12.59
..    ...              ...        ...      ...
524  VIVK        Utilities   0.028424   $0.845
525  SONM        Utilities   0.012423    $2.55
526  CLRO        Utilities   0.011807  $0.4926
527  SUNE        Utilities   0.002223   $1.225
528  ALCE        Utilities   0.000000   $0.226

[503 rows x 4 columns]

In [7]:
# nodes.to_json('../stock_visualization/data/nodes.json', orient='records')
# links.to_json('../stock_visualization/data/links.json', orient='records')

In [8]:
json_data = {
    'nodes': nodes.to_dict(orient='records'),
    'links': links.to_dict(orient='records')
}

file_path = '../stock_visualization/data/beta_stock_graph_fair.json'

import json
with open(file_path, 'w') as json_file:
    json.dump(json_data, json_file, indent=4)

In [9]:
# matrix[links['source'] == 'TSLA']

In [10]:
# matrix.loc['TSLA'].sort_values(ascending=False)

In [11]:
links[links['value'] < 0]

    source target     value       abs
18   SOHON  HBANL -0.904104  0.904104
19   SOHON  VLYPO -0.881085  0.881085
28   NYMTZ  PARAA -0.906463  0.906463
29   NYMTZ   POOL -0.871178  0.871178
38   LANDM    WMG -0.922878  0.922878
..     ...    ...       ...       ...
802    CSX  METCL -0.883264  0.883264
807   PTEN   DWSN -0.881898  0.881898
814   CSCO  EXEEL -0.793834  0.793834
815    SVC  EXEEZ -0.897023  0.897023
816  EXEEZ   RIVN -0.875369  0.875369

[73 rows x 4 columns]