In [1]:
# Import packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf
import tqdm
from pathlib import Path

In [2]:
# Read data
screener_path  = Path('../data/nasdaq_screener_20250513.csv')
screener = pd.read_csv(screener_path)
snp_path  = Path('../data/snp500.csv')
snp = pd.read_csv(snp_path)
snp

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [3]:
stock = yf.download(snp['Symbol'].tolist())

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  503 of 503 completed

503 Failed downloads:
['UBER', 'NI', 'CMS', 'J', 'MTB', 'SPG', 'DVA', 'TPL', 'NWS', 'AMD', 'ISRG', 'GRMN', 'BXP', 'VZ', 'GPC', 'NKE', 'CME', 'DOC', 'BAC', 'FE', 'LYV', 'CHRW', 'ERIE', 'ROK', 'MET', 'ABBV', 'RMD', 'TSCO', 'DUK', 'XEL', 'LUV', 'CAT', 'MAA', 'BEN', 'CVS', 'CBRE', 'AWK', 'MLM', 'ESS', 'PNC', 'MKC', 'CCL', 'APTV', 'SJM', 'ENPH', 'HAS', 'USB', 'HLT', 'AMT', 'SLB', 'TSLA', 'BF.B', 'AIG', 'ANET', 'A', 'WRB', 'PPL', 'FDX', 'LULU', 'AAPL', 'STE', 'RCL', 'FOX', 'TROW', 'MNST', 'EMR', 'EQT', 'MCK', 'PSX', 'IBM', 'NSC', 'MDLZ', 'VLTO', 'ALB', 'FFIV', 'PKG', 'EPAM', 'CDNS', 'BBY', 'LKQ', 'GDDY', 'MO', 'NWSA', 'WY', 'DAY', 'BLK', 'PYPL', 'CMI', 'FICO', 'DECK', 'EMN', 'WSM', 'CRWD', 'KEY', 'GE', 'HD', 'QCOM', 'TXT', 'WYNN', 'DASH', 'V', 'DAL', 'RJF', 'SWKS', 'CRL', 'ATO', 'MAR', 'GOOG', 'LDOS', 'GD', 'RF', 'FRT', 'RSG', 'AMAT', 'UDR', 'LHX', 'GILD', 'AEE', 'AXON', 'CB', 'FDS', 'EXE', 'ADBE', 'GPN', 'CVX', 'CAG', 'WELL', 'T', 'TRMB', 'MSI', 'CPAY', 'HAL', 'HWM', 'DG', 'HOLX', 'NXPI', 'ETN', 'EQR', 'EQIX', 'PSA', 'VRSN', 'LVS', 'PCG', 'COF', 'BKR', 'RL', 'IP', 'POOL', 'META', 'KR', 'JPM', 'PRU', 'SYK', 'TAP', 'SPGI', 'TTWO', 'TER', 'FAST', 'BDX', 'CF', 'NFLX', 'PGR', 'DOW', 'ES', 'GEN', 'CPT', 'C', 'AES', 'AVB', 'AZO', 'TYL', 'SOLV', 'UNH', 'BR', 'SW', 'SBUX', 'IVZ', 'MCHP', 'ADSK', 'APD', 'CPRT', 'KMB', 'PLTR', 'ALLE', 'CFG', 'MDT', 'DFS', 'NVDA', 'RVTY', 'URI', 'PH', 'FOXA', 'PCAR', 'EXR', 'HCA', 'AFL', 'KHC', 'GLW', 'SYY', 'INTU', 'HPQ', 'WEC', 'MPWR', 'PG', 'ACGL', 'NUE', 'CSX', 'LIN', 'PHM', 'F', 'BMY', 'TDG', 'AVGO', 'PFG', 'KIM', 'FITB', 'KMI', 'AKAM', 'CTSH', 'TJX', 'LMT', 'PPG', 'ROL', 'COST', 'INTC', 'VICI', 'ALL', 'INVH', 'WDAY', 'ABT', 'ANSS', 'BRK.B', 'FANG', 'FTNT', 'COR', 'CLX', 'IR', 'LYB', 'PEP', 'AON', 'EXPE', 'GOOGL', 'BLDR', 'PNW', 'MHK', 'RTX', 'NTAP', 'IPG', 'O', 'BG', 'ED', 'ROST', 'PWR', 'TRV', 'STLD', 'ADP', 'ITW', 'MPC', 'AOS', 'KEYS', 'CPB', 'NCLH', 'AMGN', 'IFF', 'MS', 'WBA', 'PFE', 'MGM', 'SNPS', 'EBAY', 'CSGP', 'STX', 'LH', 'OTIS', 'SWK', 'DRI', 'JBHT', 'TEL', 'NDSN', 'KMX', 'D', 'GEHC', 'TMUS', 'HSIC', 'JKHY', 'KO', 'PAYX', 'MRNA', 'SRE', 'JCI', 'DE', 'OMC', 'TGT', 'LLY', 'HES', 'CCI', 'ROP', 'TDY', 'NTRS', 'PODD', 'VRTX', 'TRGP', 'APH', 'GIS', 'CARR', 'ECL', 'CHD', 'NEM', 'HST', 'CDW', 'SBAC', 'MTD', 'TSN', 'ORLY', 'BKNG', 'STZ', 'ABNB', 'MKTX', 'CHTR', 'CSCO', 'IQV', 'UNP', 'WDC', 'PM', 'CMCSA', 'EIX', 'BK', 'CI', 'ADM', 'BX', 'AVY', 'LEN', 'CTRA', 'TPR', 'ACN', 'HSY', 'ETR', 'BALL', 'DLTR', 'NEE', 'JNPR', 'NDAQ', 'ODFL', 'LOW', 'FI', 'WMT', 'CAH', 'EXPD', 'INCY', 'SO', 'NOC', 'TECH', 'COO', 'FCX', 'MSCI', 'HII', 'WFC', 'EXC', 'DIS', 'KLAC', 'ICE', 'APO', 'EL', 'BA', 'DPZ', 'HRL', 'ORCL', 'HIG', 'SMCI', 'MAS', 'MTCH', 'EG', 'ELV', 'ALGN', 'MMM', 'L', 'LNT', 'VLO', 'PARA', 'XOM', 'IT', 'AEP', 'DXCM', 'HON', 'AIZ', 'EW', 'GEV', 'TFC', 'CINF', 'OKE', 'CZR', 'IDXX', 'UPS', 'WST', 'SCHW', 'NRG', 'MCD', 'EVRG', 'NOW', 'SHW', 'VMC', 'CTAS', 'REGN', 'HBAN', 'STT', 'VRSK', 'APA', 'UAL', 'MOH', 'MSFT', 'DLR', 'UHS', 'TT', 'DHR', 'DTE', 'DVN', 'VTR', 'BRO', 'PEG', 'FTV', 'PANW', 'GS', 'AMP', 'AME', 'OXY', 'CL', 'MU', 'KDP', 'FSLR', 'HUBB', 'WBD', 'XYL', 'JBL', 'SNA', 'YUM', 'IEX', 'CNC', 'EOG', 'AMZN', 'ZBRA', 'CRM', 'LII', 'GL', 'PNR', 'CTVA', 'WAT', 'GM', 'WAB', 'LW', 'KVUE', 'ZBH', 'CBOE', 'GWW', 'NVR', 'CNP', 'WTW', 'LRCX', 'SYF', 'HPE', 'MA', 'TMO', 'BIIB', 'ADI', 'HUM', 'PTC', 'COP', 'GNRC', 'CMG', 'DELL', 'CEG', 'PLD', 'IRM', 'AXP', 'PAYC', 'BAX', 'TKO', 'WM', 'EFX', 'K', 'ARE', 'MMC', 'DOV', 'EA', 'MRK', 'DD', 'MCO', 'REG', 'JNJ', 'VST', 'WMB', 'DGX', 'AJG', 'VTRS', 'TXN', 'KKR', 'DHI', 'FIS', 'MOS', 'ULTA', 'ON', 'BSX', 'AMCR', 'ZTS']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')

In [4]:
stock.columns

MultiIndex([('Adj Close',    'A'),
            ('Adj Close', 'AAPL'),
            ('Adj Close', 'ABBV'),
            ('Adj Close', 'ABNB'),
            ('Adj Close',  'ABT'),
            ('Adj Close', 'ACGL'),
            ('Adj Close',  'ACN'),
            ('Adj Close', 'ADBE'),
            ('Adj Close',  'ADI'),
            ('Adj Close',  'ADM'),
            ...
            (   'Volume',  'WTW'),
            (   'Volume',   'WY'),
            (   'Volume', 'WYNN'),
            (   'Volume',  'XEL'),
            (   'Volume',  'XOM'),
            (   'Volume',  'XYL'),
            (   'Volume',  'YUM'),
            (   'Volume',  'ZBH'),
            (   'Volume', 'ZBRA'),
            (   'Volume',  'ZTS')],
           names=['Price', 'Ticker'], length=3018)

In [5]:
stock.to_csv('../data/snp500_stock_all_time_raw.csv')

In [6]:
stock_filtered = stock.copy()
stock_filtered = stock_filtered['Close']
stock_filtered = stock_filtered[stock_filtered.index >= '2023-01-01']
stock_filtered = stock_filtered.dropna(axis=1)
stock_filtered

Empty DataFrame
Columns: [A, AAPL, ABBV, ABNB, ABT, ACGL, ACN, ADBE, ADI, ADM, ADP, ADSK, AEE, AEP, AES, AFL, AIG, AIZ, AJG, AKAM, ALB, ALGN, ALL, ALLE, AMAT, AMCR, AMD, AME, AMGN, AMP, AMT, AMZN, ANET, ANSS, AON, AOS, APA, APD, APH, APO, APTV, ARE, ATO, AVB, AVGO, AVY, AWK, AXON, AXP, AZO, BA, BAC, BALL, BAX, BBY, BDX, BEN, BF.B, BG, BIIB, BK, BKNG, BKR, BLDR, BLK, BMY, BR, BRK.B, BRO, BSX, BX, BXP, C, CAG, CAH, CARR, CAT, CB, CBOE, CBRE, CCI, CCL, CDNS, CDW, CEG, CF, CFG, CHD, CHRW, CHTR, CI, CINF, CL, CLX, CMCSA, CME, CMG, CMI, CMS, CNC, ...]
Index: []

[0 rows x 503 columns]

In [7]:
stock_filtered.to_csv('../data/snp500_stock_2023_cleaned.csv')